version: '3'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123123
    ports:
      - "3307:3307"

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    restart: always
    ports:
      - "8080:8080"
    environment:
      - spring.jpa.hibernate.ddl-auto=update
      - spring.datasource.url=jdbc:mysql://mysql:3306/quizlet_clone?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=123123
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver